# Generated by Django 5.0.6 on 2024-06-08 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='products.category',
            ),
        ),
        migrations.AddField(
            model_name='basket',
            name='product_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='products.product',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user_id', 'product_id')},
        ),
    ]
